# Generated by Django 5.1.4 on 2024-12-06 03:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Transaction Name')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('bill_no', models.PositiveIntegerField(unique=True, verbose_name='Bill Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('pay_option', models.CharField(choices=[('personal', 'Personal'), ('salary', 'Salary'), ('rent', 'Rent'), ('office', 'Office')], default='personal', max_length=20, verbose_name='Payment Option')),
                ('bill_date', models.DateTimeField(auto_now_add=True, verbose_name='Bill Date')),
            ],
            options={
                'verbose_name': 'Day Book Entry',
                'verbose_name_plural': 'Day Book Entries',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('order_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Order Date & Time')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
            ],
            options={
                'verbose_name': 'Final Order',
                'verbose_name_plural': 'Final Orders',
                'ordering': ['-order_date_time'],
            },
        ),
        migrations.CreateModel(
            name='MainCourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=200, unique=True, verbose_name='Main Course Name')),
            ],
            options={
                'verbose_name': 'Main Course Name',
                'verbose_name_plural': 'Main Course Names',
                'ordering': ['main_name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Item Name')),
                ('description', models.TextField(verbose_name='Item Description')),
                ('image_url', models.URLField(verbose_name='Item Image URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item Price')),
                ('main_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.maincoursename', verbose_name='Main Course')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['main_course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be alphanumeric', regex='^\\w+$')], verbose_name='Username')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('table_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Table Number')),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number', regex='^\\d{10,15}$')], verbose_name='Contact Number')),
            ],
            options={
                'verbose_name': 'User Table',
                'verbose_name_plural': 'User Tables',
                'ordering': ['table_no'],
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='finalorder',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='api.menuitem', verbose_name='Ordered Item'),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='user_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.usertable', verbose_name='User Table'),
        ),
    ]
